# Generated by Django 5.0.1 on 2024-01-16 10:55

import base.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_options_user_cash_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='latest_price',
            field=base.models.PositiveDecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_history',
            field=models.TextField(max_length=100000, null=True),
        ),
    ]
