# Generated by Django 5.0.1 on 2024-01-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_stock_latest_price_stock_stock_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='latest_price',
            new_name='price',
        ),
    ]
