# Generated by Django 5.0.1 on 2024-01-17 01:30

import base.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_transfer_date_transfer_time_transfer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedstock',
            name='current_quantity',
            field=base.models.PositiveDecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
