# Generated by Django 5.0.1 on 2024-01-17 10:38

import base.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_ownedstock_current_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedstock',
            name='average_price',
            field=base.models.PositiveDecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RemoveField(
            model_name='ownedstock',
            name='transaction_history',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cash',
            field=base.models.PositiveDecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ownedstock',
            name='transaction_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.transaction'),
        ),
    ]
