# Generated by Django 5.0.1 on 2024-01-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_ownedstock_average_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedstock',
            old_name='average_price',
            new_name='average_cost_price',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='_price',
        ),
    ]
