# Generated by Django 5.0.1 on 2024-01-20 05:45

import base.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_average_price_ownedstock_average_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='value',
            field=base.models.PositiveDecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
