# Generated by Django 5.0.1 on 2024-01-20 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_transfer_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['owned_stock']},
        ),
        migrations.RemoveField(
            model_name='ownedstock',
            name='transaction_history',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stock',
        ),
        migrations.AddField(
            model_name='transaction',
            name='owned_stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ownedstock'),
        ),
    ]
