# Generated by Django 5.0.1 on 2024-01-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date', 'time']},
        ),
    ]
