# Generated by Django 5.0.1 on 2024-02-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tz',
            field=models.CharField(default='Asia/Singapore', max_length=50),
        ),
    ]
