# Generated by Django 5.0.1 on 2024-02-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_transaction_options_remove_transaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='time',
        ),
        migrations.AddField(
            model_name='transfer',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
