# Generated by Django 5.0.1 on 2024-02-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_transfer_date_remove_transfer_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
