# Generated by Django 5.0.1 on 2024-02-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_transaction_datetime_alter_transfer_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='method',
            field=models.CharField(choices=[('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('set', 'Set')], max_length=10),
        ),
    ]
