# Generated by Django 5.0.1 on 2024-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_transfer_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
