# Generated by Django 5.0.1 on 2024-02-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_ownedstock_realised_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hc',
            field=models.CharField(choices=[('USD', 'United States Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound Sterling'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('HKD', 'Hong Kong Dollar'), ('SGD', 'Singapore Dollar')], default='SGD', max_length=50, verbose_name='Home Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(verbose_name='Date & Time'),
        ),
    ]
