# Generated by Django 5.0.1 on 2024-02-12 05:50

import base.models
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_user_hc_alter_transaction_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfrom', models.CharField(max_length=3)),
                ('cto', models.CharField(max_length=3)),
                ('crate', base.models.PositiveDecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='ownedstock',
            name='realised_pnl',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
    ]
