# Generated by Django 5.0.1 on 2024-02-12 06:16

import base.models
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_currencyconversionrate_alter_ownedstock_realised_pnl'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyconversionrate',
            unique_together={('cfrom', 'cto')},
        ),
        migrations.AddField(
            model_name='currencyconversionrate',
            name='_ccrate',
            field=base.models.PositiveDecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='currencyconversionrate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='currencyconversionrate',
            name='crate',
        ),
    ]
