# Generated by Django 5.0.1 on 2024-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_currencyconversionrate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(choices=[('NASDAQ', 'NASDAQ'), ('NYSE', 'NYSE'), ('NYSEARCA', 'NYSEARCA')], max_length=10, null=True),
        ),
    ]
